# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentbox < Formula
  desc "Generate devcontainer setups for AI coding agents"
  homepage "https://github.com/BjRo/agentbox"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/BjRo/agentbox/releases/download/v0.2.0/agentbox_0.2.0_darwin_amd64.tar.gz"
      sha256 "34d6a0e775cc7825b916f2a7b1a092d219a953898ec93240d7d50b183099f235"

      define_method(:install) do
        bin.install "agentbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/BjRo/agentbox/releases/download/v0.2.0/agentbox_0.2.0_darwin_arm64.tar.gz"
      sha256 "2f07ffcc35840a3cc043e70005addebc3bd85e57e429bcea909d6ea0281f2311"

      define_method(:install) do
        bin.install "agentbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/BjRo/agentbox/releases/download/v0.2.0/agentbox_0.2.0_linux_amd64.tar.gz"
      sha256 "58c36014047c65f95d824022e45647c6a33b25c456344e6fbd5ae51e626d49ac"
      define_method(:install) do
        bin.install "agentbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BjRo/agentbox/releases/download/v0.2.0/agentbox_0.2.0_linux_arm64.tar.gz"
      sha256 "9715603bec0e579af723ad3d5a55ca313b8f61d99590cc446b496db2b4a672f6"
      define_method(:install) do
        bin.install "agentbox"
      end
    end
  end

  test do
    system "#{bin}/agentbox", "--version"
  end
end
