# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccbox < Formula
  desc "Generate devcontainer setups for Claude Code"
  homepage "https://github.com/BjRo/ccbox"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/BjRo/ccbox/releases/download/v0.1.0/ccbox_0.1.0_darwin_amd64.tar.gz"
      sha256 "f655f076b38f4189b63be4aced269ea6d5551e20ce74c6cdc23432b8a1a02b25"

      define_method(:install) do
        bin.install "ccbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/BjRo/ccbox/releases/download/v0.1.0/ccbox_0.1.0_darwin_arm64.tar.gz"
      sha256 "5a1e86f451cc56ed805d90e261082c062a220552add83792450c1dd0c998c6cd"

      define_method(:install) do
        bin.install "ccbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/BjRo/ccbox/releases/download/v0.1.0/ccbox_0.1.0_linux_amd64.tar.gz"
      sha256 "cc2a1edaba4046edbb8eb8da5fab6b544150f70f931f47ae5a8fbd55cbddf21a"
      define_method(:install) do
        bin.install "ccbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BjRo/ccbox/releases/download/v0.1.0/ccbox_0.1.0_linux_arm64.tar.gz"
      sha256 "078becfb646225262c9e387e600553f03c72c36be32290b731f3df67086091f3"
      define_method(:install) do
        bin.install "ccbox"
      end
    end
  end

  test do
    system "#{bin}/ccbox", "--version"
  end
end
